"""Generate FAQPage JSON-LD schema for top 20 product pages.

Adds 5–8 Q&As per product based on product type, tags, and existing description.
Output: schema snippets ready to embed in Shopify product description (top of HTML body).
"""
import json
import time
import urllib.request
from pathlib import Path

CREDS_PATH = Path.home() / ".claude/credentials.json"


def _gemini_key() -> str:
    return json.loads(CREDS_PATH.read_text())["api_keys"]["gemini"]


def gemini(prompt: str, max_tokens: int = 1500) -> str:
    key = _gemini_key()
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={key}"
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.5, "maxOutputTokens": max_tokens, "responseMimeType": "application/json"},
    }
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"}, method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        d = json.loads(r.read().decode())
    parts = d.get("candidates", [{}])[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts).strip()


def build_faq_for_product(product: dict, brand: str = "Dark Fantasy") -> dict:
    title = product.get("title", "")
    ptype = product.get("productType") or ""
    tags = product.get("tags") or []
    seo_d = (product.get("seo") or {}).get("description") or ""

    prompt = f"""Generate 6 customer FAQs for a Shopify product page. Output strict JSON: {{"faqs": [{{"q": "...", "a": "..."}}]}}.

Product: {title}
Type: {ptype}
Tags: {', '.join(tags[:8])}
Description: {seo_d}
Brand: {brand}

Each Q must be a real customer question (use natural phrasing). Each A must be 60–140 chars, factual, and reassuring on safety/discreet shipping where relevant. Cover: materials, cleaning/care, sizing/fit, beginner-friendly use, shipping discretion, and return policy. Output strict JSON only — no preamble, no Markdown."""

    try:
        raw = gemini(prompt)
        data = json.loads(raw)
        faqs = data.get("faqs", [])
    except Exception as e:
        return {"product_id": product.get("id"), "title": title, "error": str(e)[:200]}

    schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": f.get("q", ""),
                "acceptedAnswer": {"@type": "Answer", "text": f.get("a", "")},
            }
            for f in faqs if f.get("q") and f.get("a")
        ],
    }

    # Build the HTML snippet to paste into product description
    qa_html = "\n".join(
        f'<details><summary>{f["q"]}</summary><p>{f["a"]}</p></details>'
        for f in faqs if f.get("q") and f.get("a")
    )
    schema_html = f'<script type="application/ld+json">\n{json.dumps(schema, indent=2)}\n</script>'

    return {
        "product_id": product.get("id"),
        "title": title,
        "handle": product.get("handle"),
        "faqs": faqs,
        "schema_jsonld": schema,
        "snippet_to_embed_in_description": (
            "<!-- FAQ block — generated by seo-geo-weekly -->\n"
            '<section class="product-faq" aria-label="Frequently asked questions">\n'
            "<h3>Frequently asked questions</h3>\n"
            f"{qa_html}\n"
            "</section>\n"
            f"{schema_html}"
        ),
    }


def run(state_dir: Path, top_n: int = 20) -> dict:
    catalog = json.loads((state_dir / "catalog.json").read_text())
    # Pick top N active products by tags / type variety
    products = [p for p in catalog["products"] if p.get("status") == "ACTIVE"][:top_n]

    out = []
    for i, p in enumerate(products, 1):
        print(f"      [faq] {i}/{len(products)} {p.get('title', '')[:60]}")
        out.append(build_faq_for_product(p))
        time.sleep(0.5)

    (state_dir / "product_faqs.json").write_text(json.dumps(out, indent=2))
    return {"count": len(out), "ok": sum(1 for r in out if "schema_jsonld" in r)}


if __name__ == "__main__":
    import sys
    state = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "state" / "2026-05-08"
    print(run(state, top_n=int(sys.argv[2]) if len(sys.argv) > 2 else 20))
